[#status]
image:https://img.shields.io/badge/License-LGPL%20v3-blue.svg[link="https://www.gnu.org/licenses/lgpl-3.0"]
image:https://img.shields.io/badge/License-FDL%20v1.3-blue.svg[link="https://www.gnu.org/licenses/fdl-1.3"]
image:https://api.bintray.com/packages/funthomas424242/funthomas424242-libs/rades.scaffolding/images/download.svg[link="https://bintray.com/funthomas424242/funthomas424242-libs/rades.scaffolding/_latestVersion"]
image:https://travis-ci.org/FunThomas424242/rades.scaffolding.svg?branch=master["Build Status", link="https://travis-ci.org/FunThomas424242/rades.scaffolding"]
image:https://api.codacy.com/project/badge/Grade/64f23754fdc1426a9216521cf5362d71["Codacy code quality", link="https://www.codacy.com/app/FunThomas424242/rades.scaffolding?utm_source=github.com&utm_medium=referral&utm_content=FunThomas424242/rades.scaffolding&utm_campaign=Badge_Grade"]
image:https://codecov.io/gh/FunThomas424242/rades.scaffolding/branch/master/graph/badge.svg[link="https://codecov.io/gh/FunThomas424242/rades.scaffolding"]
image:https://badge.waffle.io/FunThomas424242/rades.scaffolding.svg?columns=all["Waffle.io - Columns and their card count", link="https://waffle.io/FunThomas424242/rades.scaffolding"]

# rades.scaffolding
Ein RADES Subprojekt zur Generierung benötigter Projektstrukturen - Aufsetzen von RADES styled Projekten

## Generelle Eigenschaften von RADES Projekten

* Der Sourcekode wird auf github gehostet und per ssh ausgecheckt
* Es wird ein Maven Starter verwendet, damit das Projekt auf jeder Plattform mit der
  gleichen Maven Version gebaut und entwickelt werden kann.
* Build mittels Maven und pom.xml
* Build prüft ob es aktuellere Version der Projek- oder Buildabhängigkeiten gibt
* Versionierung sollte semantisch erfolgen
* Dokumentation wird per asciidoc erstellt
* Die Dokumentation wird in das Unterverzeichnis /docs generiert damit es sich auf github als site festlegen lässt
* Diagramme werden per plantuml generiert
* Release Bau erfolgt manuell, da der Maven Weg zu mühsam ist
* Im Projektverzeichnis liegen README.adoc, LICENSE und Changelog.adoc
* Ignoredfiles werden über .gitignore ausgeschlossen
* IDE spezifische Files werden nicht eingecheckt
* Editoreinstellungen werden über .editorconfig festgelegt
* CI erfolgt über Travis-ci und es wird der Maven Starter statt maven direkt aufgerufen
* Anforderungsabarbeitung erfolgt über waffle.io
* Codingstyle wird über codacy geprüft
* Testüberdeckung erfolgt durch codecov
* Qualität der Testfälle wird über Mutationstests mit Framework pitest.org geprüft
* Testfälle werden mit JUnit5 ausgeführt - nur wo 3th party libs JUnit4 benötigen wird beides supported
* Neue Feature werden als issues in waffle.io eingestellt und über Branches
  deren Name #issueId vorangestellt wird bearbeitet
* Das umgesetzte Feature wird über Pull Request in den master gemerged
*


## Konzept

Das Projekt stellt Annotationen auf Package Level bereit. Diese können in Java Projekten über die Datei package-info.java
verwendet werden. Die Annotationen können zur Generierung bestimmter Teile von RADES styled Projekten genutzt werden.
Die wichtigste Annotation für den nachfolgenden Generierungprozess ist die @Radesprojekt Annotation.
Die im folgenden beschriebenen Aspekte eines RADES Projektes sind für weitere Konfigurationen relevant.


### Maven Build

RADES Projekte werden im allgemeinen über maven gebaut und verteilt. Damit dies möglichst auf jeder Plattform funktioniert wird
der https://www.baeldung.com/maven-wrapper[Maven Wrapper] verwendet. Dieser wird über die
@Maven Annotation erzeugt. Er kann im Projektwurzelverzeichnis auch manuell erzeugt werden:

`mvn -N io.takari:maven:wrapper -Dmaven=3.6.0`

Zur Steuerung des Builds wird eine pom.xml Datei benötigt. Diese wird automatisch bei Verwendung
der @Maven Annotation mit angelegt.

#### Beispiel

.package-info.java
[source, java]
----
package com.github.funthomas424242.rades-validations;
@Project( //<1>
    @GroupId("com.github.funthomas424242") //<2>
    @ArtifactId("rades-validations") //<3>
    @Version("1.0.0-SNAPSHOT") //<4>
    @Rades  //<5>
    @Maven //<6>
    @AsciiDoc //<7>
)
----

<1> Konfiguration der Projekstruktur.
<2> GroupId (analog zu Maven).
<3> ArtifactId (analog zu Maven).
<4> Version (analog zu Maven).
<5> Projektstyle: Rades (radesstyled project).
<6> Unterstützung für das Buildsystem Maven wird mit generiert.
<7> Unterstützung für das Dokumentationssystem asciidoc wird mit generiert.


# Quellen im Neuland

* https://www.intertech.com/Blog/whats-package-info-java-for/
*
